services:
  api:
    build: ./api
    ports:
      - "8001:9001"
    env_file: .env
    depends_on:
      - minio

  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - api

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
